### ISSUE TITLE
stuck exercise 10 where do ı have mistake ? 

### ISSUE THREAD

**Issue by SirmaXX** [zwilias/elm-demystify-decoders#7]
```elm
module Exercise10 exposing (Person, PersonDetails, Role(..), decoder)

import Json.Decode exposing (Decoder, fail, map3, string, int, list, field, map2, succeed, andThen, map)

type alias Person =
    { username : String
    , role : Role
    , details : PersonDetails
    }


type alias PersonDetails =
    { registered : String
    , aliases : List String
    }


type Role
    = Newbie
    | Regular
    | OldFart



decoder : Decoder (List Person)
decoder =
 list decoderPerson

decoderPerson : Decoder Person
decoderPerson =
   map3 Person  
      decoderUsername 
      decoderRole 
      decoderDetails


decoderUsername : Decoder String
decoderUsername=
  (field "username" string)

decoderRole : Decoder Role
decoderRole=
  map roleDecoder (field "role" string)


roleDecoder : String -> Role
roleDecoder role =
    case String.toLower role of
        "newbie" ->
             Newbie

        "regular" ->
            Regular

        "oldfart" ->
             OldFart

        _ ->
             Newbie


decoderDetails : Decoder PersonDetails
decoderDetails =
  map2 PersonDetails
  (field "registered" string)
  (field "aliases " (list string))
```

when ı run the test elm-test tests/Exercise10 it say 
```
Exercise10.Tests
↓ Exercise 10
✗ Decodes random people

    This test failed because it threw an exception: "RangeError: Maximum call stack size exceeded"
```

where do ı have  a mistake

**Comment by zwilias** [comment]
Try to construct JSON based _only_ on the definitions of your decoders:

`decoderPerson` combines 3 decoders:
- `decoderUsername` which uses `field "username"`
- `decoderRole` which uses `field "role"`
- `decoderDetails` which uses `field "registered"` and `field "aliases"`

So, it looks for JSON like
```javascript
{
  "username": ...,
  "role": ...,
  "registered": ...,
  "aliases": ...
}
```

Note that this does not quite match what the input JSON looks like! The JSON that it will actually try to decode has a `details` field which contains those `registered` and `aliases` fields.

So, if you were to use `decoderDetails` as `field "details" decoderDetails`, it would be "scoped" to the correct field.

----

Unrelated: I would recommend changing your `decoderRole` to use `andThen`/`succeed`/`fail`, so you can fail the entire decoder when the input-JSON has an invalid role in it, rather than mapping all unexpected input to `Newbie`. There is no test for this, currently, but I should probably add one anyway :D
